<script setup lang="ts">
import { ref, watch } from 'vue'
import type { DayBriefing } from '@smartskip/shared'
import { api } from '@/api/client'

const props = defineProps<{ date: string }>()

const briefing = ref<DayBriefing | null>(null)
const loading = ref(false)
const error = ref<string | null>(null)

async function load(): Promise<void> {
  loading.value = true
  error.value = null

  try {
    briefing.value = await api.getBriefing(props.date)
  } catch (cause) {
    error.value = cause instanceof Error ? cause.message : 'Failed to load briefing'
  } finally {
    loading.value = false
  }
}

watch(() => props.date, load, { immediate: true })
</script>

<template>
  <section class="panel">
    <header class="panel__header">
      <h2>Daily briefing</h2>
      <button class="button" :disabled="loading" @click="load">Regenerate</button>
    </header>

    <p v-if="loading" class="panel__state">Thinking…</p>
    <p v-else-if="error" class="panel__state panel__state--error">{{ error }}</p>

    <template v-else-if="briefing">
      <p class="briefing__headline">{{ briefing.headline }}</p>

      <ul v-if="briefing.items.length" class="briefing__items">
        <li
          v-for="item in briefing.items"
          :key="`${item.jobId}-${item.message}`"
          class="briefing__item"
          :class="`briefing__item--${item.severity}`"
        >
          {{ item.message }}
        </li>
      </ul>

      <p class="briefing__source">
        Generated by the <strong>{{ briefing.source }}</strong> provider. The weather and
        routing behind it are still stubs, so there is not much for it to say yet.
      </p>
    </template>
  </section>
</template>
